### ISSUE TITLE
with  tampermonkey in chrome ?

### ISSUE THREAD

**Issue by alexseyk** [justinikeako/darklingo#4]
Any chance you can make your extension work via tampermonkey in chrome ?  It works but the scheme is off. 
<img width="866" alt="Screen Shot 2020-11-26 at 13 14 45" src="https://user-images.githubusercontent.com/60418150/100314539-6eef6400-2fe9-11eb-9b40-5aa7e75ef67e.png">

 The reason i am asking is that duoleavemealone (https://github.com/derat/duoleavemealone) does not work when i install your script via stylus

**Comment by justinikeako** [comment]
Seems to work fine with Stylus & Stylish but not Tampermonkey for some reason... I'll be looking into it. Hopefully this should be fixed by the end of the week.

**Comment by justinikeako** [comment]
I see the issue now. The script installed places the style in the head causing it to be overwritten by other styles further in the document. To fix it you're going to have to change the code manually as I don't think the developers of Userstyles are willing to update that portion.

Scroll to the end of the script & you should see the following if/else statement.
```
if (heads.length > 0) {
	heads[0].appendChild(node);
} else {
	// no head yet, stick it whereever
	document.documentElement.appendChild(node);
}
```
In order to get the style to function properly, you'll have to replace that chunk of code with the following:

`document.documentElement.appendChild(node);`

It's a hotfix, I know, but unless I were to fork Userstyles completely, (which I have considered), I'm afraid this is the best I can do for now. Hope this helps!

**Comment by justinikeako** [comment]
Apparently, not even the customization features get carried over. Seriously considering making my own version of this service next year...

**Comment by alexseyk** [comment]
Ok, it fixed the color schema, however duoleavemealone stopped working :( [https://github.com/derat/duoleavemealone](url)

**Comment by justinikeako** [comment]
Then I believe it's an issue of incompatibility between the two, unfortunately :((

**Comment by justinikeako** [comment]
Will look into it further though. Maybe I'll be able to change something with my style to fix the problem.

**Comment by alexseyk** [comment]
As i understand it. This has something to do with the color / background of the green "continue" button.   When it is not changed, the leaveme script works.. BTW It still works with https://chrome.google.com/webstore/detail/dark-mode/dmghijelimhndkbmpgbldicpogfkceaj but they have messed up the color schemes (Themes type B), so it does not look so good any more.

**Comment by justinikeako** [comment]
After further inspection, I'm not too sure I can fix this compatibility issue if not for the degradation of my style's quality. I'll try contacting the developer to learn more though.
